language: go

go: # Go maintains the last two versions https://golang.org/doc/devel/release.html#policy
    - tip
    - "1.10"
    - 1.9.x
allow_failures:
    - go: tip
script:
    - go test -race -v ./...
    - $HOME/gopath/bin/goveralls -service=travis-ci
# For coveralls.io
before_install:
    - go get github.com/mattn/goveralls
