language: go

go: # Go maintains the last two versions. As of July 2017, 1.8.3 is current.
    - tip
    - 1.8
    - 1.7
allow_failures:
    - go: tip
before_script:
    - go vet ./...
script:
    - go test -race -v ./...
    - $HOME/gopath/bin/goveralls -service=travis-ci
# For coveralls.io
before_install:
    - go get github.com/mattn/goveralls
